export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"1 Mose"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"2 Mose"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"3 Mose"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"4 Mose"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"5 Mose"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"Josua"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"Richter"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"Rut"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"1 Samuel"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"2 Samuel"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"1 Könige"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"2 Könige"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"1 Chronik"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"2 Chronik"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"Esra"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"Nehemia"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"Ester"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"Hiob"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"Psalm"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"Sprüche"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"Prediger"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"Hohelied"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"Jesaja"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"Jeremia"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"Klagelieder"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"Hesekiel"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"Daniel"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"Hosea"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"Joel"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"Amos"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"Obadja"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"Jona"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"Micha"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"Nahum"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"Habakuk"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"Zephanja"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"Haggai"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"Sacharja"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"Maleachi"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"Matthäus"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"Markus"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"Lukas"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"Johannes"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"Apostelgeschichte"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"Römer"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"1. Korinther"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"2. Korinther"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"Galater"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"Epheser"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"Philipper"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"Kolosser"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"1. Thessalonicher"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"2. Thessalonicher"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"1. Timotheus"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"2. Timotheus"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"Titus"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"Philemon"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"Hebräer"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"Jakobus"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"1. Petrus"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"2. Petrus"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"1. Johannes"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"2. Johannes"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"3. Johannes"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"Judas"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"Offenbarung"}
];
