//https://www.ellopos.net/elpenor/greek-texts/new-testament/default.asp
//https://www.ellopos.net/elpenor/greek-texts/septuagint/default.asp
export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"ΓΕΝΕΣΙΣ"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"ΕΞΟΔΟΣ"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"ΛΕΥΙΤΙΚΟΝ"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"ΑΡΙΘΜΟΙ"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"ΔΕΥΤΕΡΟΝΟΜΙΟΝ"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"ΙΗΣΟΥΣ ΝΑΥΗ"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"ΚΡΙΤΑΙ"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"ΡΟΥΘ"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"ΒΑΣΙΛΕΙΩΝ Α"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"ΒΑΣΙΛΕΙΩΝ Β"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"ΒΑΣΙΛΕΙΩΝ Γ"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"ΒΑΣΙΛΕΙΩΝ Δ"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Α"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Β"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"ΕΣΔΡΑΣ"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"ΝΕΕΜΙΑΣ"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"ΕΣΘΗΡ"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"ΙΩΒ"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"ΨΑΛΜΟΙ"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"ΠΑΡΟΙΜΙΑΙ ΣΟΛΟΜΩΝΤΟΣ"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"ΕΚΚΛΗΣΙΑΣΤΗΣ"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"ΑΣΜΑ ΑΣΜΑΤΩΝ"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"ΗΣΑΪΑΣ"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"ΙΕΡΕΜΙΑΣ"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"ΘΡΗΝΟΙ ΙΕΡΕΜΙΟΥ"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"ΙΕΖΕΚΙΗΛ"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"ΔΑΝΙΗΛ"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"ΩΣΗΕ"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"ΙΩΗΛ"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"ΑΜΩΣ"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"ΟΒΔΙΟΥ"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"ΙΩΝΑΣ"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"ΜΙΧΑΙΑΣ"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"ΝΑΟΥΜ"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"ΑΜΒΑΚΟΥΜ"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"ΣΟΦΟΝΙΑΣ"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"ΑΓΓΑΙΟΣ"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"ΖΑΧΑΡΙΑΣ"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"ΜΑΛΑΧΙΑΣ"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"ΚΑΤΑ ΜΑΤΘΑΙΟΝ"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"ΚΑΤΑ ΜΑΡΚΟΝ"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"ΚΑΤΑ ΛΟΥΚΑΝ"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"ΚΑΤΑ ΙΩΑΝΝΗΝ"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"ΠΡΑΞΕΙΣ ΤΩΝ ΑΠΟΣΤΟΛΩΝ"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"ΠΡΟΣ ΡΩΜΑΙΟΥΣ"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Α΄"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β΄"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"ΠΡΟΣ ΓΑΛΑΤΑΣ"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"ΠΡΟΣ ΕΦΕΣΙΟΥΣ"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α΄"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β΄"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"ΠΡΟΣ ΤΙΜΟΘΕΟΝ Α΄"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"ΠΡΟΣ ΤΙΜΟΘΕΟΝ Β΄"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"ΠΡΟΣ ΤΙΤΟΝ"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"ΠΡΟΣ ΦΙΛΗΜΟΝΑ"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"ΠΡΟΣ ΕΒΡΑΙΟΥΣ"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"ΙΑΚΩΒΟΥ"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"ΠΕΤΡΟΥ Α΄"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"ΠΕΤΡΟΥ Β΄"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"ΙΩΑΝΝΟΥ Α΄"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"ΙΩΑΝΝΟΥ Β΄"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"ΙΩΑΝΝΟΥ Γ΄"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"ΙΟΥΔΑ"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"ΑΠΟΚΑΛΥΨΙΣ ΙΩΑΝΝΟΥ"}
];
