export default [
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"Matthew"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"Mark"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"Luke"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"John"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"Acts"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"Romans"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"1 Corinthians"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"2 Corinthians"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"Galatians"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"Ephesians"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"Philippians"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"Colossians"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"1 Thessalonians"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"2 Thessalonians"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"1 Timothy"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"2 Timothy"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"Titus"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"Philemon"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"Hebrews"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"James"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"1 Peter"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"2 Peter"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"1 John"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"2 John"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"3 John"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"Jude"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"Revelation"}
];
