export default [
{chapter:"50",value: "Gen",label:"創世記"},
{chapter:"40",value: "Exo",label:"出埃及記"},
{chapter:"27",value: "Lev",label:"利未記"},
{chapter:"36",value: "Num",label:"民數記"},
{chapter:"34",value: "Deu",label:"申命記"},
{chapter:"24",value: "Jos",label:"約書亞記"},
{chapter:"21",value:"Jug",label:"士師記"},
{chapter:"4",value:"Rut",label:"路得記"},
{chapter:"31",value:"1Sa",label:"撒母耳記上"},
{chapter:"24",value:"2Sa",label:"撒母耳記下"},
{chapter:"22",value:"1Ki",label:"列王紀上"},
{chapter:"25",value:"2Ki",label:"列王紀下"},
{chapter:"29",value:"1Ch",label:"歷代志上"},
{chapter:"36",value:"2Ch",label:"歷代志下"},
{chapter:"10",value:"Ezr",label:"以斯拉記"},
{chapter:"13",value:"Neh",label:"尼希米記"},
{chapter:"10",value:"Est",label:"以斯帖記"},
{chapter:"42",value:"Job",label:"約伯記"},
{chapter:"150",value:"Psm",label:"詩篇"},
{chapter:"31",value:"Pro",label:"箴言"},
{chapter:"12",value:"Ecc",label:"傳道書"},
{chapter:"8",value:"Son",label:"雅歌"},
{chapter:"66",value:"Isa",label:"以賽亞書"},
{chapter:"52",value:"Jer",label:"耶利米書"},
{chapter:"5",value:"Lam",label:"耶利米哀歌"},
{chapter:"48",value:"Eze",label:"以西結書"},
{chapter:"12",value:"Dan",label:"但以理書"},
{chapter:"14",value:"Hos",label:"何西阿書"},
{chapter:"3",value:"Joe",label:"約珥書"},
{chapter:"9",value:"Amo",label:"阿摩司書"},
{chapter:"1",value:"Oba",label:"俄巴底亞書"},
{chapter:"4",value:"Jon",label:"約拿書"},
{chapter:"7",value:"Mic",label:"彌迦書"},
{chapter:"3",value:"Nah",label:"那鴻書"},
{chapter:"3",value:"Hab",label:"哈巴谷書"},
{chapter:"3",value:"Zep",label:"西番雅書"},
{chapter:"2",value:"Hag",label:"哈該書"},
{chapter:"14",value:"Zec",label:"撒迦利亞書"},
{chapter:"4",value:"Mal",label:"瑪拉基書"},
{chapter:"28",value:"Mat",label:"馬太福音"},
{chapter:"16",value:"Mak",label:"馬可福音"},
{chapter:"24",value:"Luk",label:"路加福音"},
{chapter:"21",value:"Jhn",label:"約翰福音"},
{chapter:"28",value:"Act",label:"使徒行傳"},
{chapter:"16",value:"Rom",label:"羅馬書"},
{chapter:"16",value:"1Co",label:"哥林多前書"},
{chapter:"13",value:"2Co",label:"哥林多後書"},
{chapter:"6",value:"Gal",label:"加拉太書"},
{chapter:"6",value:"Eph",label:"以弗所書"},
{chapter:"4",value:"Phl",label:"腓立比書"},
{chapter:"4",value:"Col",label:"歌羅西書"},
{chapter:"5",value:"1Ts",label:"帖撒羅尼迦前書"},
{chapter:"3",value:"2Ts",label:"帖撒羅尼迦後書"},
{chapter:"6",value:"1Ti",label:"提摩太前書"},
{chapter:"4",value:"2Ti",label:"提摩太後書"},
{chapter:"3",value:"Tit",label:"提多書"},
{chapter:"1",value:"Phm",label:"腓利門書"},
{chapter:"13",value:"Heb",label:"希伯來書"},
{chapter:"5",value:"Jas",label:"雅各書"},
{chapter:"5",value:"1Pe",label:"彼得前書"},
{chapter:"3",value:"2Pe",label:"彼得後書"},
{chapter:"5",value:"1Jn",label:"約翰壹書"},
{chapter:"1",value:"2Jn",label:"約翰貳書"},
{chapter:"1",value:"3Jn",label:"約翰參書"},
{chapter:"1",value:"Jud",label:"猶大書"},
{chapter:"22",value:"Rev",label:"啟示錄"}
];
