export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"בראשית"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"ואלה שמות"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"ויקרא"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"במדבר"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"אלה הדברים"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"יהושע"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"שפטים"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"רות"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"שמואל א"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"שמואל ב"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"מלכים א"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"מלכים ב"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"דברי הימים א"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"דברי הימים ב"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"עזרא"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"נחמיה"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"אסתר"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"איוב"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"תהלים"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"משלי"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"קהלת"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"שיר השירים"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"ישעיה"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"ירמיה"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"איכה"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"יחזקאל"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"דניאל"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"הושע"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"יואל"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"עמוס"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"עבדיה"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"יונה"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"מיכה"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"נחום"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"חבקוק"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"צפניה"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"חגי"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"זכריה"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"מלאכי"}
];
