export default [
{chapter:"50",value: "Gen",label:"Genesis"},
{chapter:"40",value: "Exo",label:"Exodus"},
{chapter:"27",value: "Lev",label:"Leviticus"},
{chapter:"36",value: "Num",label:"Numbers"},
{chapter:"34",value: "Deu",label:"Deuteronomy"},
{chapter:"24",value: "Jos",label:"Joshua"},
{chapter:"21",value:"Jug",label:"Judges"},
{chapter:"4",value:"Rut",label:"Ruth"},
{chapter:"31",value:"1Sa",label:"1 Samuel"},
{chapter:"24",value:"2Sa",label:"2 Samuel"},
{chapter:"22",value:"1Ki",label:"1 Kings"},
{chapter:"25",value:"2Ki",label:"2 Kings"},
{chapter:"29",value:"1Ch",label:"1 Chronicles"},
{chapter:"36",value:"2Ch",label:"2 Chronicles"},
{chapter:"10",value:"Ezr",label:"Ezra"},
{chapter:"13",value:"Neh",label:"Nehemiah"},
{chapter:"10",value:"Est",label:"Esther"},
{chapter:"42",value:"Job",label:"Job"},
{chapter:"150",value:"Psm",label:"Psalms"},
{chapter:"31",value:"Pro",label:"Proverbs"},
{chapter:"12",value:"Ecc",label:"Ecclesiastes"},
{chapter:"8",value:"Son",label:"Song of Songs"},
{chapter:"66",value:"Isa",label:"Isaiah"},
{chapter:"52",value:"Jer",label:"Jeremiah"},
{chapter:"5",value:"Lam",label:"Lamentations"},
{chapter:"48",value:"Eze",label:"Ezekiel"},
{chapter:"12",value:"Dan",label:"Daniel"},
{chapter:"14",value:"Hos",label:"Hosea"},
{chapter:"3",value:"Joe",label:"Joel"},
{chapter:"9",value:"Amo",label:"Amos"},
{chapter:"1",value:"Oba",label:"Obadiah"},
{chapter:"4",value:"Jon",label:"Jonah"},
{chapter:"7",value:"Mic",label:"Micah"},
{chapter:"3",value:"Nah",label:"Nahum"},
{chapter:"3",value:"Hab",label:"Habakkuk"},
{chapter:"3",value:"Zep",label:"Zephaniah"},
{chapter:"2",value:"Hag",label:"Haggai"},
{chapter:"14",value:"Zec",label:"Zechariah"},
{chapter:"4",value:"Mal",label:"Malachi"},
{chapter:"28",value:"Mat",label:"Matthew"},
{chapter:"16",value:"Mak",label:"Mark"},
{chapter:"24",value:"Luk",label:"Luke"},
{chapter:"21",value:"Jhn",label:"John"},
{chapter:"28",value:"Act",label:"Acts"},
{chapter:"16",value:"Rom",label:"Romans"},
{chapter:"16",value:"1Co",label:"1 Corinthians"},
{chapter:"13",value:"2Co",label:"2 Corinthians"},
{chapter:"6",value:"Gal",label:"Galatians"},
{chapter:"6",value:"Eph",label:"Ephesians"},
{chapter:"4",value:"Phl",label:"Philippians"},
{chapter:"4",value:"Col",label:"Colossians"},
{chapter:"5",value:"1Ts",label:"1 Thessalonians"},
{chapter:"3",value:"2Ts",label:"2 Thessalonians"},
{chapter:"6",value:"1Ti",label:"1 Timothy"},
{chapter:"4",value:"2Ti",label:"2 Timothy"},
{chapter:"3",value:"Tit",label:"Titus"},
{chapter:"1",value:"Phm",label:"Philemon"},
{chapter:"13",value:"Heb",label:"Hebrews"},
{chapter:"5",value:"Jas",label:"James"},
{chapter:"5",value:"1Pe",label:"1 Peter"},
{chapter:"3",value:"2Pe",label:"2 Peter"},
{chapter:"5",value:"1Jn",label:"1 John"},
{chapter:"1",value:"2Jn",label:"2 John"},
{chapter:"1",value:"3Jn",label:"3 John"},
{chapter:"1",value:"Jud",label:"Jude"},
{chapter:"22",value:"Rev",label:"Revelation"}
];
