export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"창세기"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"탈출기"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"레위기"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"민수기"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"신명기"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"여호수아"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"재판관기"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"룻"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"사무엘 첫째"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"사무엘 둘째"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"열왕기 첫째"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"열왕기 둘째"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"역대기 첫째"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"역대기 둘째"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"에스라"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"느헤미야"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"에스더"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"욥"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"시편"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"잠언"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"전도서"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"솔로몬의 노래"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"이사야"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"예레미야"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"애가"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"에스겔"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"다니엘"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"호세아"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"요엘"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"아모스"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"오바댜"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"요나"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"미가"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"나훔"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"하박국"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"스바냐"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"학개"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"스가랴"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"말라기"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"마태"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"마가"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"누가"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"요한"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"사도"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"로마"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"고린도 첫째"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"고린도 둘째"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"갈라디아"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"에베소"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"빌립보"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"골로새"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"데살로니가 첫째"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"데살로니가 둘째"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"디모데 첫째"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"디모데 둘째"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"디도"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"빌레몬"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"히브리"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"야고보"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"베드로 첫째"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"베드로 둘째"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"요한 첫째"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"요한 둘째"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"요한 셋째"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"유다"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"계시록"}
];
