export default [
{chapter:"50",value: "Gen",nameTW:"創世記"},
{chapter:"40",value: "Exo",nameTW:"出埃及記"},
{chapter:"27",value: "Lev",nameTW:"利未記"},
{chapter:"36",value: "Num",nameTW:"民數記"},
{chapter:"34",value: "Deu",nameTW:"申命記"},
{chapter:"24",value: "Jos",nameTW:"約書亞記"},
{chapter:"21",value:"Jug",nameTW:"士師記"},
{chapter:"4",value:"Rut",nameTW:"路得記"},
{chapter:"31",value:"1Sa",nameTW:"撒母耳記上"},
{chapter:"24",value:"2Sa",nameTW:"撒母耳記下"},
{chapter:"22",value:"1Ki",nameTW:"列王紀上"},
{chapter:"25",value:"2Ki",nameTW:"列王紀下"},
{chapter:"29",value:"1Ch",nameTW:"歷代志上"},
{chapter:"36",value:"2Ch",nameTW:"歷代志下"},
{chapter:"10",value:"Ezr",nameTW:"以斯拉記"},
{chapter:"13",value:"Neh",nameTW:"尼希米記"},
{chapter:"10",value:"Est",nameTW:"以斯帖記"},
{chapter:"42",value:"Job",nameTW:"約伯記"},
{chapter:"150",value:"Psm",nameTW:"詩篇"},
{chapter:"31",value:"Pro",nameTW:"箴言"},
{chapter:"12",value:"Ecc",nameTW:"傳道書"},
{chapter:"8",value:"Son",nameTW:"雅歌"},
{chapter:"66",value:"Isa",nameTW:"以賽亞書"},
{chapter:"52",value:"Jer",nameTW:"耶利米書"},
{chapter:"5",value:"Lam",nameTW:"耶利米哀歌"},
{chapter:"48",value:"Eze",nameTW:"以西結書"},
{chapter:"12",value:"Dan",nameTW:"但以理書"},
{chapter:"14",value:"Hos",nameTW:"何西阿書"},
{chapter:"3",value:"Joe",nameTW:"約珥書"},
{chapter:"9",value:"Amo",nameTW:"阿摩司書"},
{chapter:"1",value:"Oba",nameTW:"俄巴底亞書"},
{chapter:"4",value:"Jon",nameTW:"約拿書"},
{chapter:"7",value:"Mic",nameTW:"彌迦書"},
{chapter:"3",value:"Nah",nameTW:"那鴻書"},
{chapter:"3",value:"Hab",nameTW:"哈巴谷書"},
{chapter:"3",value:"Zep",nameTW:"西番雅書"},
{chapter:"2",value:"Hag",nameTW:"哈該書"},
{chapter:"14",value:"Zec",nameTW:"撒迦利亞書"},
{chapter:"4",value:"Mal",nameTW:"瑪拉基書"},
{chapter:"28",value:"Mat",nameTW:"馬太福音"},
{chapter:"16",value:"Mak",nameTW:"馬可福音"},
{chapter:"24",value:"Luk",nameTW:"路加福音"},
{chapter:"21",value:"Jhn",nameTW:"約翰福音"},
{chapter:"28",value:"Act",nameTW:"使徒行傳"},
{chapter:"16",value:"Rom",nameTW:"羅馬書"},
{chapter:"16",value:"1Co",nameTW:"哥林多前書"},
{chapter:"13",value:"2Co",nameTW:"哥林多後書"},
{chapter:"6",value:"Gal",nameTW:"加拉太書"},
{chapter:"6",value:"Eph",nameTW:"以弗所書"},
{chapter:"4",value:"Phl",nameTW:"腓立比書"},
{chapter:"4",value:"Col",nameTW:"歌羅西書"},
{chapter:"5",value:"1Ts",nameTW:"帖撒羅尼迦前書"},
{chapter:"3",value:"2Ts",nameTW:"帖撒羅尼迦後書"},
{chapter:"6",value:"1Ti",nameTW:"提摩太前書"},
{chapter:"4",value:"2Ti",nameTW:"提摩太後書"},
{chapter:"3",value:"Tit",nameTW:"提多書"},
{chapter:"1",value:"Phm",nameTW:"腓利門書"},
{chapter:"13",value:"Heb",nameTW:"希伯來書"},
{chapter:"5",value:"Jas",nameTW:"雅各書"},
{chapter:"5",value:"1Pe",nameTW:"彼得前書"},
{chapter:"3",value:"2Pe",nameTW:"彼得後書"},
{chapter:"5",value:"1Jn",nameTW:"約翰壹書"},
{chapter:"1",value:"2Jn",nameTW:"約翰貳書"},
{chapter:"1",value:"3Jn",nameTW:"約翰參書"},
{chapter:"1",value:"Jud",nameTW:"猶大書"},
{chapter:"22",value:"Rev",nameTW:"啟示錄"}
];
