export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"創世記"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"出エジプト記"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"レビ記"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"民数記"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"申命記"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"ヨシュア記"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"士師記"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"ルツ記"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"サムエル記第一"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"サムエル記第二"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"列王記第一"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"列王記第二"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"歴代誌第一"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"歴代誌第二"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"エズラ記"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"ネヘミア記"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"エステル記"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"ヨブ記"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"詩篇"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"箴言"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"伝道者の書"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"雅歌"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"イザヤ書"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"エレミア書"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"哀歌"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"エゼキエル書"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"ダニエル書"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"ホセア書"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"ヨエル書"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"アモス書"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"オバデア書"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"ヨナ書"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"ミカ書"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"ナホム書"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"ハバクク書"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"ゼパニア書"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"ハガイ書"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"ゼカリア書"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"マラキ書"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"マタイの福音書"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"マルコの福音書"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"ルカの福音書"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"ヨハネの福音書"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"使徒の働き"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"ローマ人への手紙"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"コリント人への手紙第一"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"コリント人への手紙第二"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"ガラテア人への手紙"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"エペソ人への手紙"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"ピリピ人への手紙"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"コロサイ人への手紙"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"テサロニケ人への手紙第一"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"テサロニケ人への手紙第二"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"テモテへの手紙第一"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"テモテへの手紙第二"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"テトスへの手紙"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"ピレモンへの手紙"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"ヘブル人への手紙"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"ヤコブの手紙"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"ペテロの手紙第一"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"ペテロの手紙第二"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"ヨハネの手紙第一"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"ヨハネの手紙第二"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"ヨハネの手紙第三"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"ユダの手紙"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"ヨハネの黙示録"}
];
