export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"Genèse"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"Exode"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"Lévitique"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"Nombres"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"Deutéronome"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"Josué"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"Juges"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"Ruth"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"1 Samuel"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"2 Samuel"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"1 Rois"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"2 Rois"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"1 Chroniques"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"2 Chroniques"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"Esdras"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"Néhémie"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"Esther"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"Job"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"Psaumes"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"Proverbes"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"Ecclésiaste"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"Cantique des Cantiques"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"Ésaïe"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"Jérémie"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"Lamentations"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"Ézéchiel"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"Daniel"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"Osée"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"Joël"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"Amos"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"Abdias"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"Jonas"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"Michée"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"Nahum"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"Habacuc"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"Sophonie"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"Aggée"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"Zacharie"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"Malachie"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"Matthieu"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"Marc"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"Luc"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"Jean"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"Actes"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"Romains"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"1 Corinthiens"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"2 Corinthiens"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"Galates"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"Éphésiens"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"Philippiens"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"Colossiens"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"1 Thessaloniciens"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"2 Thessaloniciens"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"1 Timothée"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"2 Timothée"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"Tite"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"Philémon"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"Hébreux"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"Jacques"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"1 Pierre"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"2 Pierre"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"1 Jean"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"2 Jean"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"3 Jean"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"Jude"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"Apocalypse"}
];
