export default [
{key:"",chapter:"50",value: "Gen",label:"Genesis"},
{key:"",chapter:"40",value: "Exo",label:"Exodus"},
{key:"",chapter:"27",value: "Lev",label:"Leviticus"},
{key:"",chapter:"36",value: "Num",label:"Numbers"},
{key:"",chapter:"34",value: "Deu",label:"Deuteronomy"},
{key:"",chapter:"24",value: "Jos",label:"Joshua"},
{key:"",chapter:"21",value:"Jug",label:"Judges"},
{key:"",chapter:"4",value:"Rut",label:"Ruth"},
{key:"",chapter:"31",value:"1Sa",label:"1 Samuel"},
{key:"",chapter:"24",value:"2Sa",label:"2 Samuel"},
{key:"",chapter:"22",value:"1Ki",label:"1 Kings"},
{key:"",chapter:"25",value:"2Ki",label:"2 Kings"},
{key:"",chapter:"29",value:"1Ch",label:"1 Chronicles"},
{key:"",chapter:"36",value:"2Ch",label:"2 Chronicles"},
{key:"",chapter:"10",value:"Ezr",label:"Ezra"},
{key:"",chapter:"13",value:"Neh",label:"Nehemiah"},
{key:"",chapter:"10",value:"Est",label:"Esther"},
{key:"",chapter:"42",value:"Job",label:"Job"},
{key:"",chapter:"150",value:"Psm",label:"Psalms"},
{key:"",chapter:"31",value:"Pro",label:"Proverbs"},
{key:"",chapter:"12",value:"Ecc",label:"Ecclesiastes"},
{key:"",chapter:"8",value:"Son",label:"Song of Songs"},
{key:"",chapter:"66",value:"Isa",label:"Isaiah"},
{key:"",chapter:"52",value:"Jer",label:"Jeremiah"},
{key:"",chapter:"5",value:"Lam",label:"Lamentations"},
{key:"",chapter:"48",value:"Eze",label:"Ezekiel"},
{key:"",chapter:"12",value:"Dan",label:"Daniel"},
{key:"",chapter:"14",value:"Hos",label:"Hosea"},
{key:"",chapter:"3",value:"Joe",label:"Joel"},
{key:"",chapter:"9",value:"Amo",label:"Amos"},
{key:"",chapter:"1",value:"Oba",label:"Obadiah"},
{key:"",chapter:"4",value:"Jon",label:"Jonah"},
{key:"",chapter:"7",value:"Mic",label:"Micah"},
{key:"",chapter:"3",value:"Nah",label:"Nahum"},
{key:"",chapter:"3",value:"Hab",label:"Habakkuk"},
{key:"",chapter:"3",value:"Zep",label:"Zephaniah"},
{key:"",chapter:"2",value:"Hag",label:"Haggai"},
{key:"",chapter:"14",value:"Zec",label:"Zechariah"},
{key:"",chapter:"4",value:"Mal",label:"Malachi"},
{key:"",chapter:"28",value:"Mat",label:"Matthew"},
{key:"",chapter:"16",value:"Mak",label:"Mark"},
{key:"",chapter:"24",value:"Luk",label:"Luke"},
{key:"",chapter:"21",value:"Jhn",label:"John"},
{key:"",chapter:"28",value:"Act",label:"Acts"},
{key:"",chapter:"16",value:"Rom",label:"Romans"},
{key:"",chapter:"16",value:"1Co",label:"1 Corinthians"},
{key:"",chapter:"13",value:"2Co",label:"2 Corinthians"},
{key:"",chapter:"6",value:"Gal",label:"Galatians"},
{key:"",chapter:"6",value:"Eph",label:"Ephesians"},
{key:"",chapter:"4",value:"Phl",label:"Philippians"},
{key:"",chapter:"4",value:"Col",label:"Colossians"},
{key:"",chapter:"5",value:"1Ts",label:"1 Thessalonians"},
{key:"",chapter:"3",value:"2Ts",label:"2 Thessalonians"},
{key:"",chapter:"6",value:"1Ti",label:"1 Timothy"},
{key:"",chapter:"4",value:"2Ti",label:"2 Timothy"},
{key:"",chapter:"3",value:"Tit",label:"Titus"},
{key:"",chapter:"1",value:"Phm",label:"Philemon"},
{key:"",chapter:"13",value:"Heb",label:"Hebrews"},
{key:"",chapter:"5",value:"Jas",label:"James"},
{key:"",chapter:"5",value:"1Pe",label:"1 Peter"},
{key:"",chapter:"3",value:"2Pe",label:"2 Peter"},
{key:"",chapter:"5",value:"1Jn",label:"1 John"},
{key:"",chapter:"1",value:"2Jn",label:"2 John"},
{key:"",chapter:"1",value:"3Jn",label:"3 John"},
{key:"",chapter:"1",value:"Jud",label:"Jude"},
{key:"",chapter:"22",value:"Rev",label:"Revelation"}
];
