export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"創世記"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"出埃及記"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"利未記"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"民數記"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"申命記"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"約書亞記"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"士師記"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"路得記"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"撒母耳記上"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"撒母耳記下"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"列王紀上"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"列王紀下"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"歷代志上"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"歷代志下"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"以斯拉記"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"尼希米記"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"以斯帖記"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"約伯記"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"詩篇"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"箴言"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"傳道書"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"雅歌"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"以賽亞書"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"耶利米書"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"耶利米哀歌"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"以西結書"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"但以理書"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"何西阿書"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"約珥書"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"阿摩司書"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"俄巴底亞書"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"約拿書"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"彌迦書"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"那鴻書"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"哈巴谷書"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"西番雅書"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"哈該書"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"撒迦利亞書"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"瑪拉基書"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"馬太福音"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"馬可福音"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"路加福音"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"約翰福音"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"使徒行傳"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"羅馬書"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"哥林多前書"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"哥林多後書"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"加拉太書"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"以弗所書"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"腓立比書"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"歌羅西書"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"帖撒羅尼迦前書"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"帖撒羅尼迦後書"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"提摩太前書"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"提摩太後書"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"提多書"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"腓利門書"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"希伯來書"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"雅各書"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"彼得前書"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"彼得後書"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"約翰壹書"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"約翰貳書"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"約翰參書"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"猶大書"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"啟示錄"}
];
