export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"Genesis"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"Exodus"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"Leviticus"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"Numbers"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"Deuteronomy"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"Joshua"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"Judges"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"Ruth"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"1 Samuel"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"2 Samuel"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"1 Kings"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"2 Kings"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"1 Chronicles"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"2 Chronicles"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"Ezra"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"Nehemiah"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"Esther"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"Job"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"Psalms"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"Proverbs"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"Ecclesiastes"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"Song of Songs"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"Isaiah"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"Jeremiah"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"Lamentations"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"Ezekiel"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"Daniel"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"Hosea"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"Joel"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"Amos"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"Obadiah"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"Jonah"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"Micah"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"Nahum"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"Habakkuk"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"Zephaniah"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"Haggai"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"Zechariah"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"Malachi"}
];
