export default [
{key:"",searchKey:"Genesis",chapter:"50",value: "Gen",label:"Genesis"},
{key:"",searchKey:"Exodus",chapter:"40",value: "Exo",label:"Exodus"},
{key:"",searchKey:"Leviticus",chapter:"27",value: "Lev",label:"Leviticus"},
{key:"",searchKey:"Numbers",chapter:"36",value: "Num",label:"Numbers"},
{key:"",searchKey:"Deuteronomy",chapter:"34",value: "Deu",label:"Deuteronomy"},
{key:"",searchKey:"Joshua",chapter:"24",value: "Jos",label:"Joshua"},
{key:"",searchKey:"Judges",chapter:"21",value:"Jug",label:"Judges"},
{key:"",searchKey:"Ruth",chapter:"4",value:"Rut",label:"Ruth"},
{key:"",searchKey:"1 Samuel",chapter:"31",value:"1Sa",label:"1 Samuel"},
{key:"",searchKey:"2 Samuel",chapter:"24",value:"2Sa",label:"2 Samuel"},
{key:"",searchKey:"1 Kings",chapter:"22",value:"1Ki",label:"1 Kings"},
{key:"",searchKey:"2 Kings",chapter:"25",value:"2Ki",label:"2 Kings"},
{key:"",searchKey:"1 Chronicles",chapter:"29",value:"1Ch",label:"1 Chronicles"},
{key:"",searchKey:"2 Chronicles",chapter:"36",value:"2Ch",label:"2 Chronicles"},
{key:"",searchKey:"Ezra",chapter:"10",value:"Ezr",label:"Ezra"},
{key:"",searchKey:"Nehemiah",chapter:"13",value:"Neh",label:"Nehemiah"},
{key:"",searchKey:"Esther",chapter:"10",value:"Est",label:"Esther"},
{key:"",searchKey:"Job",chapter:"42",value:"Job",label:"Job"},
{key:"",searchKey:"Psalms",chapter:"150",value:"Psm",label:"Psalms"},
{key:"",searchKey:"Proverbs",chapter:"31",value:"Pro",label:"Proverbs"},
{key:"",searchKey:"Ecclesiastes",chapter:"12",value:"Ecc",label:"Ecclesiastes"},
{key:"",searchKey:"Song of Songs",chapter:"8",value:"Son",label:"Song of Songs"},
{key:"",searchKey:"Isaiah",chapter:"66",value:"Isa",label:"Isaiah"},
{key:"",searchKey:"Jeremiah",chapter:"52",value:"Jer",label:"Jeremiah"},
{key:"",searchKey:"Lamentations",chapter:"5",value:"Lam",label:"Lamentations"},
{key:"",searchKey:"Ezekiel",chapter:"48",value:"Eze",label:"Ezekiel"},
{key:"",searchKey:"Daniel",chapter:"12",value:"Dan",label:"Daniel"},
{key:"",searchKey:"Hosea",chapter:"14",value:"Hos",label:"Hosea"},
{key:"",searchKey:"Joel",chapter:"3",value:"Joe",label:"Joel"},
{key:"",searchKey:"Amos",chapter:"9",value:"Amo",label:"Amos"},
{key:"",searchKey:"Obadiah",chapter:"1",value:"Oba",label:"Obadiah"},
{key:"",searchKey:"Jonah",chapter:"4",value:"Jon",label:"Jonah"},
{key:"",searchKey:"Micah",chapter:"7",value:"Mic",label:"Micah"},
{key:"",searchKey:"Nahum",chapter:"3",value:"Nah",label:"Nahum"},
{key:"",searchKey:"Habakkuk",chapter:"3",value:"Hab",label:"Habakkuk"},
{key:"",searchKey:"Zephaniah",chapter:"3",value:"Zep",label:"Zephaniah"},
{key:"",searchKey:"Haggai",chapter:"2",value:"Hag",label:"Haggai"},
{key:"",searchKey:"Zechariah",chapter:"14",value:"Zec",label:"Zechariah"},
{key:"",searchKey:"Malachi",chapter:"4",value:"Mal",label:"Malachi"},
{key:"",searchKey:"Matthew",chapter:"28",value:"Mat",label:"Matthew"},
{key:"",searchKey:"Mark",chapter:"16",value:"Mak",label:"Mark"},
{key:"",searchKey:"Luke",chapter:"24",value:"Luk",label:"Luke"},
{key:"",searchKey:"John",chapter:"21",value:"Jhn",label:"John"},
{key:"",searchKey:"Acts",chapter:"28",value:"Act",label:"Acts"},
{key:"",searchKey:"Romans",chapter:"16",value:"Rom",label:"Romans"},
{key:"",searchKey:"1 Corinthians",chapter:"16",value:"1Co",label:"1 Corinthians"},
{key:"",searchKey:"2 Corinthians",chapter:"13",value:"2Co",label:"2 Corinthians"},
{key:"",searchKey:"Galatians",chapter:"6",value:"Gal",label:"Galatians"},
{key:"",searchKey:"Ephesians",chapter:"6",value:"Eph",label:"Ephesians"},
{key:"",searchKey:"Philippians",chapter:"4",value:"Phl",label:"Philippians"},
{key:"",searchKey:"Colossians",chapter:"4",value:"Col",label:"Colossians"},
{key:"",searchKey:"1 Thessalonians",chapter:"5",value:"1Ts",label:"1 Thessalonians"},
{key:"",searchKey:"2 Thessalonians",chapter:"3",value:"2Ts",label:"2 Thessalonians"},
{key:"",searchKey:"1 Timothy",chapter:"6",value:"1Ti",label:"1 Timothy"},
{key:"",searchKey:"2 Timothy",chapter:"4",value:"2Ti",label:"2 Timothy"},
{key:"",searchKey:"Titus",chapter:"3",value:"Tit",label:"Titus"},
{key:"",searchKey:"Philemon",chapter:"1",value:"Phm",label:"Philemon"},
{key:"",searchKey:"Hebrews",chapter:"13",value:"Heb",label:"Hebrews"},
{key:"",searchKey:"James",chapter:"5",value:"Jas",label:"James"},
{key:"",searchKey:"1 Peter",chapter:"5",value:"1Pe",label:"1 Peter"},
{key:"",searchKey:"2 Peter",chapter:"3",value:"2Pe",label:"2 Peter"},
{key:"",searchKey:"1 John",chapter:"5",value:"1Jn",label:"1 John"},
{key:"",searchKey:"2 John",chapter:"1",value:"2Jn",label:"2 John"},
{key:"",searchKey:"3 John",chapter:"1",value:"3Jn",label:"3 John"},
{key:"",searchKey:"Jude",chapter:"1",value:"Jud",label:"Jude"},
{key:"",searchKey:"Revelation",chapter:"22",value:"Rev",label:"Revelation"}
];
