export default [
  { key: '', value: 'cut', label: '繁體和合本' },
  { key: '', value: 'cus', label: '简体和合本' },
  { key: '', value: 'cnt', label: '繁體新譯本' },
  { key: '', value: 'luther1545', label: 'Deutsch Luther 1545' },
  { key: '', value: 'kjv', label: 'English KJV' },
  { key: '', value: 'web', label: 'English WEB' },
  { key: '', value: 'asv', label: 'English ASV' },
  { key: '', value: 'basicenglish', label: 'English BBE' },
  { key: '', value: 'akjv', label: 'English AKJV' },
  { key: '', value: 'valera', label: 'Reina Valera' },
  { key: '', value: 'darby', label: 'Français Darby' },
  { key: '', value: 'moderngreek', label: 'σύγχρονη εκδοχή' },
  { key: '', value: 'westcotthort', label: 'Westcott–Hort Greek NT' },
  { key: '', value: 'aleppo', label: 'כֶּתֶר אֲרָם צוֹבָא OT' },
  { key: '', value: 'modernhebrew', label: 'הגרסה מודרנית' },
  { key: '', value: 'japbungo', label: '文語訳' },
  { key: '', value: 'japkougo', label: '口語訳' },
  { key: '', value: 'korean', label: '한국어 성경' },
  { key: '', value: 'synodal', label: 'Синодальный перевод' },
  { key: '', value: 'vulgate', label: 'Vulgata Clementina' },
];
