
export const countryData = [
    { value: 'USA', name: 'USA' },
    { value: 'CANADA', name: 'CANADA' }
];

export const bibleBooks = [
{"chapter":"50", "value":"Gen", "name":"創世記"},
{"chapter":"40", "value":"Exo", "name":"出埃及記"},
{"chapter":"27", "value":"Lev", "name":"利未記"},
{"chapter":"36", "value":"Num", "name":"民數記"},
{"chapter":"34", "value":"Deu", "name":"申命記"},
{"chapter":"24", "value":"Jos", "name":"約書亞記"},
{"chapter":"21", "value":"Jug", "name":"士師記"},
{"chapter":"4", "value":"Rut", "name":"路得記"},
{"chapter":"31", "value":"1Sa", "name":"撒母耳記上"},
{"chapter":"24", "value":"2Sa", "name":"撒母耳記下"},
{"chapter":"22", "value":"1Ki", "name":"列王紀上"},
{"chapter":"25", "value":"2Ki", "name":"列王紀下"},
{"chapter":"29", "value":"1Ch", "name":"歷代志上"},
{"chapter":"36", "value":"2Ch", "name":"歷代志下"},
{"chapter":"10", "value":"Ezr", "name":"以斯拉記"},
{"chapter":"13", "value":"Neh", "name":"尼希米記"},
{"chapter":"10", "value":"Est", "name":"以斯帖記"},
{"chapter":"42", "value":"Job", "name":"約伯記"},
{"chapter":"150", "value":"Psm", "name":"詩篇"},
{"chapter":"31", "value":"Pro", "name":"箴言"},
{"chapter":"12", "value":"Ecc", "name":"傳道書"},
{"chapter":"8", "value":"Son", "name":"雅歌"},
{"chapter":"66", "value":"Isa", "name":"以賽亞書"},
{"chapter":"52", "value":"Jer", "name":"耶利米書"},
{"chapter":"5", "value":"Lam", "name":"耶利米哀歌"},
{"chapter":"48", "value":"Eze", "name":"以西結書"},
{"chapter":"12", "value":"Dan", "name":"但以理書"},
{"chapter":"14", "value":"Hos", "name":"何西阿書"},
{"chapter":"3", "value":"Joe", "name":"約珥書"},
{"chapter":"9", "value":"Amo", "name":"阿摩司書"},
{"chapter":"1", "value":"Oba", "name":"俄巴底亞書"},
{"chapter":"4", "value":"Jon", "name":"約拿書"},
{"chapter":"7", "value":"Mic", "name":"彌迦書"},
{"chapter":"3", "value":"Nah", "name":"那鴻書"},
{"chapter":"3", "value":"Hab", "name":"哈巴谷書"},
{"chapter":"3", "value":"Zep", "name":"西番雅書"},
{"chapter":"2", "value":"Hag", "name":"哈該書"},
{"chapter":"14", "value":"Zec", "name":"撒迦利亞書"},
{"chapter":"4", "value":"Mal", "name":"瑪拉基書"},
{"chapter":"28", "value":"Mat", "name":"馬太福音"},
{"chapter":"16", "value":"Mak", "name":"馬可福音"},
{"chapter":"24", "value":"Luk", "name":"路加福音"},
{"chapter":"21", "value":"Jhn", "name":"約翰福音"},
{"chapter":"28", "value":"Act", "name":"使徒行傳"},
{"chapter":"16", "value":"Rom", "name":"羅馬書"},
{"chapter":"16", "value":"1Co", "name":"哥林多前書"},
{"chapter":"13", "value":"2Co", "name":"哥林多後書"},
{"chapter":"6", "value":"Gal", "name":"加拉太書"},
{"chapter":"6", "value":"Eph", "name":"以弗所書"},
{"chapter":"4", "value":"Phl", "name":"腓立比書"},
{"chapter":"4", "value":"Col", "name":"歌羅西書"},
{"chapter":"5", "value":"1Ts", "name":"帖撒羅尼迦前書"},
{"chapter":"3", "value":"2Ts", "name":"帖撒羅尼迦後書"},
{"chapter":"6", "value":"1Ti", "name":"提摩太前書"},
{"chapter":"4", "value":"2Ti", "name":"提摩太後書"},
{"chapter":"3", "value":"Tit", "name":"提多書"},
{"chapter":"1", "value":"Phm", "name":"腓利門書"},
{"chapter":"13", "value":"Heb", "name":"希伯來書"},
{"chapter":"5", "value":"Jas", "name":"雅各書"},
{"chapter":"5", "value":"1Pe", "name":"彼得前書"},
{"chapter":"3", "value":"2Pe", "name":"彼得後書"},
{"chapter":"5", "value":"1Jn", "name":"約翰壹書"},
{"chapter":"1", "value":"2Jn", "name":"約翰貳書"},
{"chapter":"1", "value":"3Jn", "name":"約翰參書"},
{"chapter":"1", "value":"Jud", "name":"猶大書"},
{"chapter":"22", "value":"Rev", "name":"啟示錄"}
];
